# Generated by Django 6.0.7 on 2026-07-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_category_tag_alter_post_options_post_allow_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Optional introduction or legacy body. Use the ordered content blocks below for long, image-rich posts.'),
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('quote', 'Quote'), ('divider', 'Divider')], default='rich_text', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('content', models.TextField(blank=True, help_text='Used by rich-text and quote blocks.')),
                ('image', models.ImageField(blank=True, upload_to='posts/blocks/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, help_text='Required for image blocks.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('image_width', models.CharField(choices=[('content', 'Content width'), ('wide', 'Wide'), ('full', 'Full width')], default='content', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or another embeddable video URL.')),
                ('quote_attribution', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Blog.post')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'indexes': [models.Index(fields=['post', 'position'], name='blog_block_post_position_idx')],
            },
        ),
    ]
