# Generated by Django 6.0.7 on 2026-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_content_postblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
