# Generated by Django 6.0.7 on 2026-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_feedback',
            field=models.TextField(blank=True, help_text='Feedback from the admin after reviewing this post.'),
        ),
    ]
