# Generated by Django 6.0.7 on 2026-08-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_savedpost_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
