"""
Django settings for ThoughtHub project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {'1', 'true', 'yes', 'on'}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-development-only-change-before-deployment',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

if not DEBUG and (
    SECRET_KEY.startswith('django-insecure-')
    or SECRET_KEY == 'replace-with-output-from-python-secrets-token-urlsafe'
    or len(SECRET_KEY) < 50
):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a strong, unique value in production.'
    )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1',
    ).split(',')
    if host.strip()
]
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# The development frontend runs through Vite, so unsafe API requests arrive
# with the frontend origin even though Vite proxies them to Django. Production
# deployments can replace this comma-separated list in the environment.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        (
            'http://localhost:5173,http://127.0.0.1:5173'
            if DEBUG
            else FRONTEND_URL
        ),
    ).split(',')
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Blog.apps.BlogConfig',
    'Account.apps.AccountConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ThoughtHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ThoughtHub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'thoughthub'),
        'USER': os.environ.get('POSTGRES_USER', ''),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', ''),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'design']

FRONTEND_DIST_DIR = BASE_DIR / 'frontend' / 'dist'
FRONTEND_INDEX = FRONTEND_DIST_DIR / 'index.html'
if FRONTEND_DIST_DIR.exists():
    STATICFILES_DIRS.append(('frontend', FRONTEND_DIST_DIR))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Alwaysdata's free WSGI plan does not provide a separate media hostname. This
# opt-in keeps local development unchanged while allowing small personal
# deployments to serve uploaded files through Django.
SERVE_MEDIA = env_bool('DJANGO_SERVE_MEDIA', False)

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'ThoughtHub <no-reply@localhost>',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS')

# Both Caddy and Alwaysdata's front proxy send this header. Trust the forwarded
# scheme so Django generates HTTPS URLs and avoids redirect loops.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get(
    'DJANGO_SECURE_HSTS_SECONDS',
    '0' if DEBUG else '31536000',
))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.PageNumberPagination'
    ),
    'PAGE_SIZE': 10,
}

UNFOLD = {
    'SITE_TITLE': 'ThoughtHub administration',
    'SITE_HEADER': 'ThoughtHub',
    'SITE_SUBHEADER': 'Editorial workspace',
    'SITE_ICON': {
        'light': lambda request: static('logos/thoughthub-icon-light.svg'),
        'dark': lambda request: static('logos/thoughthub-icon-dark.svg'),
    },
    'SITE_LOGO': {
        'light': lambda request: static(
            'logos/thoughthub-horizontal-light.svg',
        ),
        'dark': lambda request: static(
            'logos/thoughthub-horizontal-dark.svg',
        ),
    },
    'SITE_FAVICONS': [
        {
            'rel': 'icon',
            'sizes': 'any',
            'type': 'image/svg+xml',
            'href': lambda request: static(
                'logos/thoughthub-icon-light.svg',
            ),
        },
    ],
    'BORDER_RADIUS': '8px',
    'COLORS': {
        'base': {
            '50': '#fafafa',
            '100': '#f4f4f5',
            '200': '#e4e4e7',
            '300': '#d4d4d8',
            '400': '#a1a1aa',
            '500': '#71717a',
            '600': '#52525b',
            '700': '#3f3f46',
            '800': '#27272a',
            '900': '#18181b',
            '950': '#09090b',
        },
        'primary': {
            '50': '#eff6ff',
            '100': '#dbeafe',
            '200': '#bfdbfe',
            '300': '#93c5fd',
            '400': '#60a5fa',
            '500': '#3b82f6',
            '600': '#2563eb',
            '700': '#1d4ed8',
            '800': '#1e40af',
            '900': '#1e3a8a',
            '950': '#172554',
        },
    },
    'STYLES': [
        lambda request: static('admin/unfold.css'),
    ],
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': _('Workspace'),
                'items': [
                    {
                        'title': _('Dashboard'),
                        'icon': 'space_dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                ],
            },
            {
                'title': _('Publishing'),
                'separator': True,
                'items': [
                    {
                        'title': _('Posts'),
                        'icon': 'article',
                        'link': reverse_lazy(
                            'admin:Blog_post_changelist',
                        ),
                    },
                    {
                        'title': _('Content blocks'),
                        'icon': 'view_carousel',
                        'link': reverse_lazy(
                            'admin:Blog_postblock_changelist',
                        ),
                    },
                    {
                        'title': _('Comments'),
                        'icon': 'comment',
                        'link': reverse_lazy(
                            'admin:Blog_comment_changelist',
                        ),
                    },
                ],
            },
            {
                'title': _('Organization'),
                'separator': True,
                'items': [
                    {
                        'title': _('Categories'),
                        'icon': 'category',
                        'link': reverse_lazy(
                            'admin:Blog_category_changelist',
                        ),
                    },
                    {
                        'title': _('Tags'),
                        'icon': 'sell',
                        'link': reverse_lazy(
                            'admin:Blog_tag_changelist',
                        ),
                    },
                ],
            },
            {
                'title': _('Access'),
                'separator': True,
                'items': [
                    {
                        'title': _('Users'),
                        'icon': 'group',
                        'link': reverse_lazy(
                            'admin:auth_user_changelist',
                        ),
                    },
                    {
                        'title': _('Groups'),
                        'icon': 'shield_person',
                        'link': reverse_lazy(
                            'admin:auth_group_changelist',
                        ),
                    },
                ],
            },
        ],
    },
}
