from django.urls import path

from .views import (
    AuthorCommentListView,
    AuthorPostBlockDetailView,
    AuthorPostBlockListCreateView,
    AuthorPostBlockReorderView,
    AuthorPostDetailView,
    AuthorPostListView,
    AuthorPostPublishView,
    CategoryListView,
    NotificationDetailView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationUnreadCountView,
    PublicPostCommentListCreateView,
    PublicPostDetailView,
    PublicPostListView,
    SavedPostDetailView,
    SavedPostListCreateView,
    TagListView,
)

app_name = 'blog'

urlpatterns = [
    path('posts/', PublicPostListView.as_view(), name='public-post-list'),
    path(
        'posts/<str:slug>/comments/',
        PublicPostCommentListCreateView.as_view(),
        name='public-post-comment-list',
    ),
    path(
        'posts/<str:slug>/',
        PublicPostDetailView.as_view(),
        name='public-post-detail',
    ),
    path(
        'categories/',
        CategoryListView.as_view(),
        name='category-list',
    ),
    path(
        'tags/',
        TagListView.as_view(),
        name='tag-list',
    ),
    path(
        'saved-posts/',
        SavedPostListCreateView.as_view(),
        name='saved-post-list',
    ),
    path(
        'saved-posts/<str:slug>/',
        SavedPostDetailView.as_view(),
        name='saved-post-detail',
    ),
    path(
        'notifications/',
        NotificationListView.as_view(),
        name='notification-list',
    ),
    path(
        'notifications/unread-count/',
        NotificationUnreadCountView.as_view(),
        name='notification-unread-count',
    ),
    path(
        'notifications/mark-all-read/',
        NotificationMarkAllReadView.as_view(),
        name='notification-mark-all-read',
    ),
    path(
        'notifications/<int:pk>/',
        NotificationDetailView.as_view(),
        name='notification-detail',
    ),
    path('dashboard/posts/', AuthorPostListView.as_view(), name='author-post-list'),
    path(
        'dashboard/comments/',
        AuthorCommentListView.as_view(),
        name='author-comment-list',
    ),
    path(
        'dashboard/posts/<int:pk>/',
        AuthorPostDetailView.as_view(),
        name='author-post-detail',
    ),
    path(
        'dashboard/posts/<int:pk>/publish/',
        AuthorPostPublishView.as_view(),
        name='author-post-publish',
    ),
    path(
        'dashboard/posts/<int:post_pk>/blocks/',
        AuthorPostBlockListCreateView.as_view(),
        name='author-post-block-list',
    ),
    path(
        'dashboard/posts/<int:post_pk>/blocks/reorder/',
        AuthorPostBlockReorderView.as_view(),
        name='author-post-block-reorder',
    ),
    path(
        'dashboard/posts/<int:post_pk>/blocks/<int:pk>/',
        AuthorPostBlockDetailView.as_view(),
        name='author-post-block-detail',
    ),
]
